module.exports={
    /*setUp:function(cb){
        console.log("navigating to import screen")
        this.client=this.client
        .execute(function(){
            document.getElementById('nav-open').click()
        }).pause(1000)
        .execute(function(){
            document.querySelector('a[href="#/import"]').click()
        })
        .then(()=>cb())
        .catch(console.log)
    },
    file:function(test){
        this.client
        .waitForVisible("#choose-file",3000)
        .execute(function(){
            document.getElementById('choose-file').click()
        })
        .waitForVisible("#upload-file",3000)
        .chooseFile("#upload-file",__dirname+"/../../../docs/zombie.json")
        .waitForVisible("#import-loading",3000)
        .waitForVisible("#import-success",10000)
        .execute(function(){
            document.getElementById('import-close').click()
        })
        .execute(function(){
            document.getElementById('nav-open').click()
        }).pause(1000)
        .execute(function(){
            document.querySelector('a[href="#/edit"]').click()
        })
        .waitForVisible("tbody")
        .waitForVisible("#qa-zombie-1")
        .log("browser").then(
            x=>console.log(
            x.value
            .filter(y=>y.source="console-api")
            .map(y=>y.message)
        )).then(()=>test.done())
        .catch(console.log)
    },
    url:function(test){
        test.ok(true)
        this.client.then(()=>test.done())
    }
    */
}
        
