process.env.AWS_PROFILE=require('../../../config').profile
process.env.AWS_DEFAULT_REGION=require('../../../config').profile
var handler=require('../index').handler
var Promise=require('bluebird')
var cfn=Promise.promisifyAll(require('../index'),{multiArgs:true})
var outputs=require('../../../bin/exports')

module.exports={
    error:function(test){    
        outputs('dev/master').then(function(output){
        handler({
            endpoint:output.ElasticSearchEndpoint,
            method:'HEAD',
            path:"/test/test/test",
        },{},function(error,result){
            test.ok(error)
            console.log("result:",JSON.stringify(result,null,2))
            console.log("error:",error)
            test.done()
        })
        })
    },
    get:function(test){    
        outputs('dev/master').then(function(output){
        handler({
            endpoint:output.ElasticSearchEndpoint,
            method:'GET',
            path:"/",
        },{},function(error,result){
            test.ifError(error)
            test.ok(result)
            console.log("result:",JSON.stringify(result,null,2))
            test.done()
        })
        })
    },
    post:function(test){
        outputs('dev/master').then(function(output){
        handler({
            endpoint:output.ElasticSearchEndpoint,
            method:'POST',
            path:"/"+output.ElasticSearchIndex+'/'+output.ElasticSearchType+'/test',
            body:{
                qid:"test"
            }
        },{},function(error,result){
            test.ifError(error)
            test.ok(result)
            console.log("result:",JSON.stringify(result,null,2))
            test.done()
        })
        })
    },
    bulk:function(test){    
        outputs('dev/master').then(function(output){
        handler({
            endpoint:output.ElasticSearchEndpoint,
            method:'POST',
            path:"/_bulk",
            body:[
                {delete:{
                    _index:output.ElasticSearchIndex,
                    _type:output.ElasticSearchType,
                    _id:"test-tmp.1"    
                }},
                {delete:{
                    _index:output.ElasticSearchIndex,
                    _type:output.ElasticSearchType,
                    _id:"test-tmp.2"    
                }}
            ]
        },{},function(error,result){
            console.log("error:"+JSON.stringify(error))
            test.ifError(error)
            test.ok(result)
            console.log("result:",JSON.stringify(result,null,2))
            test.done()
        })
        })
    },
    create:function(test){  
        outputs('dev/master').then(function(output){
            return cfn.CreateAsync({create:{ 
                endpoint:output.ElasticSearchEndpoint,
                method:'GET',
                path:"/"
            }})
        })
        .tap(console.log)
        .then(test.ok)
        .catch(test.ifError)
        .finally(test.done)
    },
    update:function(test){
        outputs('dev/master').then(function(output){
            return cfn.UpdateAsync("",{create:{ 
                endpoint:output.ElasticSearchEndpoint,
                method:'GET',
                path:"/"
            }},{})
        })
        .tap(console.log)
        .then(test.ok)
        .catch(test.ifError)
        .finally(test.done)
    },
    delete:function(test){
        outputs('dev/master').then(function(output){
            return cfn.DeleteAsync("",{delete:{ 
                endpoint:output.ElasticSearchEndpoint,
                method:'GET',
                path:"/"
            }})
        })
        .tap(console.log)
        .then(test.ok)
        .catch(test.ifError)
        .finally(test.done)
    }
}
