module.exports={
    stageVariables:{
        "Region":"us-east-1",
        "PoolId":"Pool-2121",
        "ClientId":"Client-adad",
        "UserPool":"User-adada",
        "ApiUrl":"url",
        "BotName":"bot",
        "Id":"id"
    },
    util:{
        parseJson:JSON.parse
    },
    context:{
        "apiId":"id" 
    }
}
