module.exports={
    "ExportBucket":{
        "Type" : "AWS::S3::Bucket",
        "Properties":{
            LifecycleConfiguration:{
                Rules:[{
                    NoncurrentVersionExpirationInDays:1,
                    Status:"Enabled"
                },{
                    AbortIncompleteMultipartUpload:{
                        DaysAfterInitiation:1
                    },
                    Status:"Enabled"
                }]
            },
            "VersioningConfiguration":{
                "Status":"Enabled"
            },
            "CorsConfiguration":{
                CorsRules:[{
                    AllowedHeaders:['*'],
                    AllowedMethods:['GET'],
                    AllowedOrigins:['*']
                }]
            }
        }
    },
    "ImportBucket":{
        "Type" : "AWS::S3::Bucket",
        "Properties":{
            LifecycleConfiguration:{
                Rules:[{
                    ExpirationInDays:1,
                    Status:"Enabled"
                }]
            },
            "VersioningConfiguration":{
                "Status":"Enabled"
            },
            "CorsConfiguration":{
                CorsRules:[{
                    AllowedHeaders:['*'],
                    AllowedMethods:['PUT'],
                    AllowedOrigins:['*']
                }]
            }
        }
    },
    "TestAllBucket":{
        "Type" : "AWS::S3::Bucket",
        "Properties":{
            LifecycleConfiguration:{
                Rules:[{
                    ExpirationInDays:1,
                    Status:"Enabled"
                }]
            },
            "VersioningConfiguration":{
                "Status":"Enabled"
            },
            "CorsConfiguration":{
                CorsRules:[{
                    AllowedHeaders:['*'],
                    AllowedMethods:['GET'],
                    AllowedOrigins:['*']
                }]
            }
        }
    }
}
