/** ************************************************************************************************
*   Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.                             *
*   SPDX-License-Identifier: Apache-2.0                                                            *
 ************************************************************************************************ */

import { config } from '@vue/test-utils';

// Stub all Vuetify components globally to suppress warnings
config.global.stubs = {
    'v-app': true,
    'v-btn': true,
    'v-card': true,
    'v-card-title': true,
    'v-card-text': true,
    'v-card-actions': true,
    'v-dialog': true,
    'v-list-subheader': true,
    'v-progress-linear': true,
    'v-spacer': true,
    'v-container': true,
    'v-row': true,
    'v-col': true,
    'v-text-field': true,
    'v-select': true,
    'v-checkbox': true,
    'v-radio': true,
    'v-radio-group': true,
    'v-switch': true,
    'v-textarea': true,
    'v-tooltip': true,
    'v-menu': true,
    'v-list': true,
    'v-list-item': true,
    'v-list-item-title': true,
    'v-list-item-subtitle': true,
    'v-divider': true,
    'v-icon': true,
    'v-badge': true,
    'v-chip': true,
    'v-avatar': true,
    'v-toolbar': true,
    'v-toolbar-title': true,
    'v-navigation-drawer': true,
    'v-footer': true,
    'v-tabs': true,
    'v-tab': true,
    'v-tab-item': true,
    'v-expansion-panels': true,
    'v-expansion-panel': true,
    'v-expansion-panel-header': true,
    'v-expansion-panel-content': true,
    'v-expansion-panel-title': true,
    'v-expansion-panel-text': true,
    'v-form': true,
    'v-layout': true,
    'v-list-group': true,
    'v-stepper': true,
    'v-table': true,
    'v-data-table-server': true,
    'v-app-bar': true,
    'v-app-bar-nav-icon': true,
    'v-app-bar-title': true,
    'v-breadcrumbs': true,
    'v-breadcrumbs-divider': true,
    'v-breadcrumbs-item': true,
    'v-toolbar-items': true,
    'router-view': true,
    'lex-web-ui': true,
};
